# Generated by Django 2.2.3 on 2019-08-01 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugCriticalSolvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=1, unique=True)),
                ('ru_name', models.CharField(max_length=40)),
                ('days_for_fix', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Критичность дефекта',
                'verbose_name_plural': 'Список уровней критичности',
                'unique_together': {('key_name', 'ru_name')},
            },
        ),
        migrations.CreateModel(
            name='ExcelFileHandle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('file_excel', models.FileField(upload_to='requests')),
                ('is_handled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Обработка файлов эксель',
                'verbose_name_plural': 'Обработка файлов эксель',
            },
        ),
        migrations.CreateModel(
            name='RequestSolvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solvo_number', models.IntegerField(unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('solvo_registered_date', models.DateTimeField()),
                ('row_created', models.DateTimeField(auto_now_add=True)),
                ('row_modified', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-solvo_registered_date'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(choices=[(1, 'ошибка/обращение'), (2, 'доработка'), (3, 'дефект')])),
                ('status_key', models.CharField(max_length=20)),
                ('ru_status_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='BugSolvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solvo_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('date_registered', models.DateTimeField()),
                ('critical_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solvo_support.BugCriticalSolvo', to_field='key_name')),
                ('status', models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='solvo_support.Status')),
            ],
            options={
                'verbose_name': 'Дефект',
                'verbose_name_plural': 'Дефекты',
            },
        ),
        migrations.CreateModel(
            name='RevisionSolvo',
            fields=[
                ('requestsolvo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='solvo_support.RequestSolvo')),
                ('solvo_revision_number', models.CharField(max_length=60, unique=True)),
                ('hours_for_develop', models.IntegerField(blank=True, null=True)),
                ('deadline_date', models.DateTimeField(blank=True, null=True)),
                ('is_accelerated', models.BooleanField(default=False)),
                ('status_revision', models.ForeignKey(default=2, limit_choices_to={'type_id': 2}, on_delete=django.db.models.deletion.PROTECT, to='solvo_support.Status')),
            ],
            options={
                'verbose_name': 'Доработка',
                'verbose_name_plural': 'Доработки',
            },
            bases=('solvo_support.requestsolvo',),
        ),
        migrations.CreateModel(
            name='RequestBugSolvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solvo_support.BugSolvo', to_field='solvo_number')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solvo_support.RequestSolvo', to_field='solvo_number')),
            ],
            options={
                'verbose_name': 'Заявка-Дефект',
                'verbose_name_plural': 'Заявки-Дефекты',
                'unique_together': {('request', 'bug')},
            },
        ),
        migrations.CreateModel(
            name='ErrorSolvo',
            fields=[
                ('requestsolvo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='solvo_support.RequestSolvo')),
                ('status_error', models.ForeignKey(default=1, limit_choices_to={'type_id': 1}, on_delete=django.db.models.deletion.PROTECT, to='solvo_support.Status')),
            ],
            options={
                'verbose_name': 'Ошибка/обращение',
                'verbose_name_plural': 'Ошибки/обращения',
            },
            bases=('solvo_support.requestsolvo',),
        ),
        migrations.CreateModel(
            name='EmailSolvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_email', models.TextField()),
                ('date_received', models.DateTimeField()),
                ('sender', models.EmailField(max_length=254)),
                ('request_solvo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solvo_support.RequestSolvo', to_field='solvo_number')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
                'unique_together': {('request_solvo', 'date_received', 'sender')},
            },
        ),
    ]
