# Generated by Django 2.2.3 on 2019-08-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solvo_support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsolvo',
            name='is_defect_registered',
            field=models.BooleanField(default=False),
        ),
    ]
